# Generated by Django 2.2.7 on 2019-11-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tourplayermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplayermodel',
            name='tour_organizer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tourplayermodel',
            name='tour_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplayermodel',
            name='tour_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
