# Generated by Django 2.2.7 on 2019-12-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_playerregistermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='high_finish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='mgmt_committee',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='nationality',
            field=models.CharField(blank=True, choices=[('American', 'American'), ('Australian', 'Australian'), ('British', 'British'), ('Canadian', 'Canadian'), ('New Zealand', 'New Zealand'), ('Swedish', 'Swedish')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='tour_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PlayerModel')),
            ],
        ),
    ]
