# Generated by Django 2.2.7 on 2019-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191204_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='nationality',
            field=models.CharField(blank=True, choices=[('American', 'American'), ('Australian', 'Australian'), ('Canadian', 'Canadian'), ('English', 'English'), ('New Zealand', 'New Zealand'), ('Swedish', 'Swedish'), ('Welsh', 'Welsh')], max_length=30, null=True),
        ),
    ]
